language: node_js
node_js:
- '8'
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/excaliburjs/ludum-41.git
script:
- chmod ugo+x deploy.sh
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./deploy.sh'